### ISSUE TITLE
joining entities

### ISSUE THREAD

**Issue by sajukassim** [HassanAzzam/Arabic-NER#1]
How can we join the B-PERS and I-PERS pair from the classified results..

**Comment by HassanAzzam** [comment]
You can consider B-PERS and I-PERS as one class (PERS for example) on top of the classified results and accumulate their counts.

**Comment by sajukassim** [comment]
Dear Sir,,
Thanks for the reply. I  am very new to python. Do you  any code sample  for that

**Comment by HassanAzzam** [comment]
Not at the mean time, unfortunately.
